//
// Created by ankit on 09.11.19.
//

#ifndef ZMQ_PUBSUB_EXAMPLE_SRC_PRODUCER_PRODUCER_H_
#define ZMQ_PUBSUB_EXAMPLE_SRC_PRODUCER_PRODUCER_H_

class producer {

};

#endif //ZMQ_PUBSUB_EXAMPLE_SRC_PRODUCER_PRODUCER_H_
